# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Funciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(363, 527)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 251, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SubirArchivo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SubirArchivo.setStyleSheet("background-color: rgb(255, 173, 79);")
        self.SubirArchivo.setObjectName("SubirArchivo")
        self.verticalLayout_3.addWidget(self.SubirArchivo)
        self.VerArchivos = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.VerArchivos.setObjectName("VerArchivos")
        self.verticalLayout_3.addWidget(self.VerArchivos)
        self.ExportarArchivos = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ExportarArchivos.setObjectName("ExportarArchivos")
        self.verticalLayout_3.addWidget(self.ExportarArchivos)
        self.Analizar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Analizar.setObjectName("Analizar")
        self.verticalLayout_3.addWidget(self.Analizar)
        self.Graficar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Graficar.setObjectName("Graficar")
        self.verticalLayout_3.addWidget(self.Graficar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 363, 21))
        self.menubar.setObjectName("menubar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSubir_Archivo = QtWidgets.QAction(MainWindow)
        self.actionSubir_Archivo.setObjectName("actionSubir_Archivo")
        self.actionVer_Archivo = QtWidgets.QAction(MainWindow)
        self.actionVer_Archivo.setObjectName("actionVer_Archivo")
        self.actionExportar_Archivo = QtWidgets.QAction(MainWindow)
        self.actionExportar_Archivo.setObjectName("actionExportar_Archivo")
        self.actionAnalizar = QtWidgets.QAction(MainWindow)
        self.actionAnalizar.setObjectName("actionAnalizar")
        self.menuAyuda.addAction(self.actionSubir_Archivo)
        self.menuAyuda.addAction(self.actionVer_Archivo)
        self.menuAyuda.addAction(self.actionExportar_Archivo)
        self.menuAyuda.addAction(self.actionAnalizar)
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Funciones"))
        self.SubirArchivo.setText(_translate("MainWindow", "Subir Archivo"))
        self.VerArchivos.setText(_translate("MainWindow", "Ver Archivos"))
        self.ExportarArchivos.setText(_translate("MainWindow", "Exportar Archivos"))
        self.Analizar.setText(_translate("MainWindow", "Analizar"))
        self.Graficar.setText(_translate("MainWindow", "Graficar"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionSubir_Archivo.setText(_translate("MainWindow", "Subir Archivo"))
        self.actionVer_Archivo.setText(_translate("MainWindow", "Ver Archivo"))
        self.actionExportar_Archivo.setText(_translate("MainWindow", "Exportar Archivo"))
        self.actionAnalizar.setText(_translate("MainWindow", "Analizar"))
